<?php
/**
 * @file
 * Code for the gsb_feature_academic_calendar_display feature.
 */

include_once 'gsb_feature_academic_calendar_display.features.inc';

function gsb_feature_academic_calendar_display_views_post_render(&$views) {
  if ($views->name != "academic_calendar") {
    return;
  }
  drupal_add_js(drupal_get_path('module', 'gsb_feature_academic_calendar_display') . '/js/gsb_feature_academic_calendar_display.js');
}
