<?php
/**
 * @file
 * Code for the gsb_feature_academic_calendar_display feature.
 */

include_once 'gsb_feature_academic_calendar_display.features.inc';

/**
 * Implements hook_views_default_views_alter().
 */
function gsb_feature_academic_calendar_display_views_default_views_alter(&$views) {
  if (isset($views['academic_calendar'])) {
    $views['academic_calendar']->display['default']->display_options['arguments']['field_academic_year_value']['default_argument_options']['argument'] = date('Y');
  }
}

function gsb_feature_academic_calendar_display_views_post_render(&$views) {

  drupal_add_js(drupal_get_path('module', 'gsb_feature_academic_calendar_display') . '/js/gsb_feature_academic_calendar_display.js');
}
